


- video: sodapoppin/2020-10/778540089
  title: "Playing VR Amoung Us! (sodapoppin) - Oct 22, 2020"
  t_start: "00:36:08"
  t_end: "04:11:56"

- video: sodapoppin/2020-10/778540089
  title: "Watching the Final Presidential Debates (with sodapoppin)"
  t_start: "04:51:36"
  t_end: "06:33:04"

- video: sodapoppin/2020-10/778540089
  title: "Jackbox Party Pack (with sodapoppin) - Oct 22, 2020"
  t_start: "08:43:48"
  t_end: "09:10:27"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/779582841
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Oct 23, 2020"
  t_start: "00:39:11"
  t_end: "05:06:03"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/780773240
  title: "Kohate (sci-fi horror) - Shitshow Saturday - Oct 24, 2020"
  t_start: "02:08:24"
  t_end: "02:33:54"

- video: sodapoppin/2020-10/780773240
  title: "Absinth (horror) - Shitshow Saturday - Oct 24, 2020"
  t_start: "02:35:31"
  t_end: "03:08:29"

- video: sodapoppin/2020-10/780773240
  title: "Murder House - Part 1 (sodapoppin) Shitshow Saturday - Oct 24, 2020"
  t_start: "03:10:34"
  t_end: "03:42:02"

- video: sodapoppin/2020-10/780773240
  title: "In Silence (multi-player horror) - Shitshow Saturday - Oct 24, 2020"
  t_start: "03:47:06"
  t_end: "05:56:00"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/781906925
  title: "Watching Random Videos (sodapoppin) - Oct 25, 2020"
  t_start: "05:33:29"
  t_end: "06:09:58"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/784892480
  title: "Murder House - Part 2 (sodapoppin) - Oct 28, 2020"
  t_start: "00:21:14"
  t_end: "02:16:54"

- video: sodapoppin/2020-10/784892480
  title: "Ghostrunner (new cyberpunk game, sodapoppin) - Oct 28, 2020"
  t_start: "02:20:16"
  t_end: "07:08:54"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/785911409
  title: "Teardown Heists Sandbox Voxel (sodapoppin) - Oct 29, 2020"
  t_start: "00:21:03"
  t_end: "01:31:48"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/786850186
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Oct 30, 2020"
  t_start: "00:11:11"
  t_end: "04:25:55"

# ===========================================
# ===========================================

- video: sodapoppin/2020-10/788070916
  title: "Friday the 13th with Friends! (sodapoppin) - Oct 31, 2020"
  t_start: "00:43:50"
  t_end: "03:26:43"

- video: sodapoppin/2020-10/788070916
  title: "SCP Secret Laboratory with Friends! (sodapoppin) - Oct 31, 2020"
  t_start: "03:27:00"
  t_end: "05:18:23"

- video: sodapoppin/2020-10/788070916
  title: "Dead by Daylight - (sodapoppin) Oct 31, 2020"
  t_start: "05:23:36"
  t_end: "06:19:07"

# ===========================================
# ===========================================

- video: sodapoppin/2020-11/789136667
  title: "Soda Plays Visage Chapters 1-3 - Nov 1, 2020"
  t_start: "02:35:15"
  t_end: "07:53:13"

- video: sodapoppin/2020-11/789136667
  title: "Sodapoppin Merch Store Shirt Competition - Nov 1, 2020"
  t_start: "00:05:39"
  t_end: "02:31:48"


# ===========================================
# ===========================================


- video: sodapoppin/2020-11/791075346
  title: "For The King Single Player (sodapoppin) - Nov 3, 2020"
  t_start: "00:36:54"
  t_end: "01:33:41"

- video: sodapoppin/2020-11/791075346
  title: "Sodapoppin Plays Pacer (racing game) - Nov 3, 2020"
  t_start: "01:40:33"
  t_end: "02:08:48"

- video: sodapoppin/2020-11/791075346
  title: "Stoneshard Part 1 (sodapoppin) - Nov 3, 2020"
  t_start: "02:12:44"
  t_end: "05:03:47"

- video: sodapoppin/2020-11/791075346
  title: "Visage Final Chapter Playthrough (sodapoppin) - Nov 3, 2020"
  t_start: "05:06:08"
  t_end: "07:40:34"


# ===========================================
# ===========================================


- video: sodapoppin/2020-11/792109101
  title: "Sodapoppin Plays Ergastulum (horror, jump scares) - Nov 4, 2020"
  t_start: "00:13:53"
  t_end: "00:39:10"

- video: sodapoppin/2020-11/792109101
  title: "Sodapoppin Plays Risk of Rain 2 - Nov 4, 2020"
  t_start: "00:40:44"
  t_end: "02:48:44"

- video: sodapoppin/2020-11/792109101
  title: "Stoneshard Part 2 (sodapoppin) - Nov 4, 2020"
  t_start: "02:51:35"
  t_end: "12:25:19"


# ===========================================
# ===========================================


- video: sodapoppin/2020-11/793136142
  title: "Stoneshard Part 3 (sodapoppin) - Nov 5, 2020"
  t_start: "00:15:27"
  t_end: "02:21:12"

- video: sodapoppin/2020-11/793136142
  title: "Sodapoppin Plays Risk of Rain 2 (sodapoppin) - Nov 5, 2020"
  t_start: "02:29:46"
  t_end: "03:19:06"

- video: sodapoppin/2020-11/793136142
  title: "VRChat Videos with Raid Trying to Avoid DMCA (sodapoppin) - Nov 5, 2020"
  t_start: "09:08:38"
  t_end: "10:07:03"


# ===========================================
# ===========================================

- video: sodapoppin/2020-11/794159919
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Nov 6, 2020"
  t_start: "00:14:56"
  t_end: "03:14:49"

- video: sodapoppin/2020-11/794159919
  title: "VRChat with Happythoughts (sodapoppin) - Nov 6, 2020"
  t_start: "09:14:53"
  t_end: "12:14:05"


# ===========================================
# ===========================================


- video: sodapoppin/2020-11/795420047
  title: "Training Happythoughts on Worms W.M.D - Nov 7, 2020"
  t_start: "00:26:30"
  t_end: "01:39:27"

- video: sodapoppin/2020-11/795420047
  title: "Sodapoppin Plays Gone Golfing (indie putt putt golf horror) - Shitshow Saturday - Nov 7, 2020"
  t_start: "01:50:00"
  t_end: "02:54:49"

- video: sodapoppin/2020-11/795420047
  title: "Sodapoppin Plays Perfect Vermin - Shitshow Saturday - Nov 7, 2020"
  t_start: "02:55:28"
  t_end: "03:16:12"

- video: sodapoppin/2020-11/795420047
  title: "Sodapoppin Plays Coldside (indie horror) - Shitshow Saturday - Nov 7, 2020"
  t_start: "03:21:27"
  t_end: "04:08:14"

- video: sodapoppin/2020-11/795420047
  title: "Sodapoppin Plays Woodle Tree Adventure - Shitshow Saturday - Nov 7, 2020"
  t_start: "04:12:01"
  t_end: "04:17:25"

- video: sodapoppin/2020-11/795420047
  title: "Dead by Daylight (sodapoppin) - Nov 7, 2020"
  t_start: "04:17:54"
  t_end: "05:11:18"

- video: sodapoppin/2020-11/795420047
  title: "Watching SCP Videos (sodapoppin) - Nov 7, 2020"
  t_start: "05:17:16"
  t_end: "05:47:56"

- video: sodapoppin/2020-11/795769633
  title: "Sodapoppin Reviews Wines - Nov 7, 2020"
  t_start: "00:05:45"
  t_end: "02:06:34"

- video: sodapoppin/2020-11/795769633
  title: "VRChat and Warcraft 3 (sodapoppin) - Nov 7, 2020"
  t_start: "02:06:34"
  t_end: "06:24:51"


# ===========================================
# ===========================================


- video: sodapoppin/2020-11/796413809
  title: "Mute vs Mute Worms Battle (sodapoppin) - Nov 8, 2020"
  t_start: "00:10:58"
  t_end: "02:47:33"

- video: sodapoppin/2020-11/796413809
  title: "Sodapoppin Plays AI Dungeon - Nov 8, 2020"
  t_start: "02:59:21"
  t_end: "04:23:59"



# ===========================================
# ===========================================


- video: sodapoppin/2020-11/797499989
  title: "Sodapoppin Plays AI Dungeon (part 2) - Nov 9, 2020"
  t_start: "00:18:12"
  t_end: "02:26:36"

- video: sodapoppin/2020-11/797499989
  title: "Sodapoppin Plays Noita (with twitch chat voting) - Nov 9, 2020"
  t_start: "02:27:58"
  t_end: "03:03:41"

# ===========================================
# ===========================================


- video: sodapoppin/2020-11/799383234
  title: "Sodapoppin Plays Risk of Rain 2 (sodapoppin) - Nov 11, 2020"
  t_start: "00:12:49"
  t_end: "00:55:44"

- video: sodapoppin/2020-11/799383234
  title: "Soda watches Wedgie Mommy (William Neff) - Nov 11, 2020"
  t_start: "00:56:40"
  t_end: "01:00:33"

- video: sodapoppin/2020-11/799383234
  title: "Cradle of Sins VR #sponsored (sodapoppin) - Nov 11, 2020"
  t_start: "01:14:52"
  t_end: "03:29:40"

- video: sodapoppin/2020-11/799729071
  title: "Sodapoppin Plays Noita (no cam) - Nov 11, 2020"
  t_start: "00:00:58"
  t_end: "04:15:46"







