
# ===========================================
# ===========================================


- video: sevadus/2020-10/782398211
  title: "Discussing Twitch VODs (part 1) - Sevadus - Oct. 26, 2020"
  t_start: "00:11:49,01:26:04,01:48:14"
  t_end: "00:34:27,01:40:03,04:17:30"


- video: sevadus/2020-10/782398211
  title: "Discussing Doctors - Sevadus - Oct. 26, 2020"
  t_start: "00:34:27"
  t_end: "01:17:56"

