

# yt_creds: 'sodapoppin_creds.json'
# yt_secrets: 'sodapoppin_secrets.json'

yt_template: 'clint_template.txt'

tags:
  - 'clintstevens'
  - 'twitch'
  - 'vod'
  - 'streamer'
  - 'clint'
  - 'super mario 64'
  - 'super mario'
  - 'nintendo'
  - 'sm64'
  - 'speedrun'
  - 'games done quick'
  - 'clonk'
  - 'mario kart'
  - 'mariokart'
  - 'games'
  - 'live'
  - 'live stream'
  - 'variety'

