- video: data/clintstevens/2020-12/840709760
  title: "120 Star Runs SM64 - (ClintStevens) - December 17, 2020"
  t_start: "00:00:00"
  t_end: "04:18:54"

- video: data/clintstevens/2020-12/845244092
  title: "120 Star Runs SM64 - (ClintStevens) - December 21, 2020"
  t_start: "00:00:00"
  t_end: "06:25:15"

- video: data/clintstevens/2020-12/846664371
  title: "120 Star Runs SM64 - (ClintStevens) - December 22, 2020"
  t_start: "00:00:00"
  t_end: "03:59:11"


- video: data/clintstevens/2020-12/847713753
  title: "120 Star Runs SM64 - (ClintStevens) - December 23, 2020"
  t_start: "00:00:00"
  t_end: "03:39:32"

- video: data/clintstevens/2020-12/847713753
  title: "16 Star Race SM64 - (ClintStevens) - December 23, 2020"
  t_start: "03:39:32"
  t_end: "04:28:34"


- video: data/clintstevens/2020-12/848850053
  title: "120 Star Runs SM64 - (ClintStevens) - December 24, 2020"
  t_start: "00:00:00"
  t_end: "04:27:35"

- video: data/clintstevens/2020-12/848850053
  title: "Worst Game Clint Has Played - (ClintStevens) - December 24, 2020"
  t_start: "00:16:24"
  t_end: "00:20:47"


- video: data/clintstevens/2020-12/850767089
  title: "120 Star Runs SM64 - (ClintStevens) - December 26, 2020"
  t_start: "00:00:00"
  t_end: "03:57:21"


- video: data/clintstevens/2021-01/860763331
  title: "120 Star Runs SM64 - (ClintStevens) - January 4, 2021"
  t_start: "00:00:00"
  t_end: "03:47:52"

- video: data/clintstevens/2021-01/889039869
  title: "120 Star Runs SM64 - (ClintStevens) - January 26, 2021"
  t_start: "00:00:00"
  t_end: "03:02:38"

- video: data/clintstevens/2021-01/890344831
  title: "120 Star Runs SM64 - (ClintStevens) - January 27, 2021"
  t_start: "00:00:00"
  t_end: "02:50:25"



- video: data/clintstevens/2021-03/944990795
  title: "Skeleton Joke - (ClintStevens) - March 10, 2021"
  t_start: "00:00:00"
  t_end: "01:12:20"

- video: data/clintstevens/2021-03/944990795
  title: "Tony Hawk's Pro Skater - (ClintStevens) - March 10, 2021"
  t_start: "01:12:20"
  t_end: "02:07:39"


- video: data/clintstevens/2021-03/957427695
  title: "Mario Kart 8 - (ClintStevens) - March 21, 2021"
  t_start: "00:00:00"
  t_end: "04:09:29"

- video: data/clintstevens/2021-06/1045248269
  title: "Pokemon Snap - (ClintStevens) - June 3, 2021"
  t_start: "00:00:00"
  t_end: "03:18:40"

- video: data/clintstevens/2021-06/1047450176
  title: "Mario Kart 8 - (ClintStevens) - June 6, 2021"
  t_start: "00:00:00"
  t_end: "04:41:11"

- video: data/clintstevens/2021-06/1049523623
  title: "Mario Kart 8 - (ClintStevens) - June 8, 2021"
  t_start: "00:00:00"
  t_end: "04:51:02"

- video: data/clintstevens/2021-06/1049523623
  title: "Clint Kills Juno - (ClintStevens) - June 8, 2021"
  t_start: "03:38:35"
  t_end: "03:43:25"


- video: data/clintstevens/2021-06/1051616384
  title: "Mario Kart 8 - (ClintStevens) - June 10, 2021"
  t_start: "00:00:00"
  t_end: "06:21:55"


- video: data/clintstevens/2021-06/1054651615
  title: "Mario Kart 8 - (ClintStevens) - June 12, 2021"
  t_start: "00:00:00"
  t_end: "06:01:09"

- video: data/clintstevens/2021-06/1055705595
  title: "Mario Kart 8 - (ClintStevens) - June 14, 2021"
  t_start: "00:00:00"
  t_end: "05:15:54"

- video: data/clintstevens/2021-06/1057740798
  title: "Mario Kart 8 - (ClintStevens) - June 16, 2021"
  t_start: "00:00:00,03:18:33"
  t_end: "02:27:12,05:05:42"

- video: data/clintstevens/2021-06/1057740798
  title: "Nintendo Direct E3 2021 - (ClintStevens) - June 16, 2021"
  t_start: "02:26:30"
  t_end: "03:19:12"

- video: data/clintstevens/2021-06/1058796307
  title: "Mario Kart 8 - (ClintStevens) - June 17, 2021"
  t_start: "00:00:00"
  t_end: "04:36:12"

- video: data/clintstevens/2021-06/1060823123
  title: "Mario Kart 8 - (ClintStevens) - June 19, 2021"
  t_start: "00:00:00"
  t_end: "04:31:50"

- video: data/clintstevens/2021-06/1060823123
  title: "Guilty Gear: Strive - (ClintStevens) - June 19, 2021"
  t_start: "04:31:50"
  t_end: "06:17:19"

- video: data/clintstevens/2021-06/1061882600
  title: "Mario Kart 8 - (ClintStevens) - June 20, 2021"
  t_start: "00:00:00"
  t_end: "04:45:17"

- video: data/clintstevens/2021-06/1064641468
  title: "Clint Vs The Streamers Mario Kart Race - (ClintStevens) - June 22, 2021"
  t_start: "00:00:00"
  t_end: "03:15:47"

- video: data/clintstevens/2021-06/1064641468
  title: "Guilty Gear: Strive - (ClintStevens) - June 22, 2021"
  t_start: "03:15:29"
  t_end: "04:04:08"

- video: data/clintstevens/2021-06/1069408511
  title: "Mario Gold Super Rush - (ClintStevens) - June 27, 2021"
  t_start: "00:00:00"
  t_end: "03:57:25"

- video: data/clintstevens/2021-06/1071945223
  title: "Mario Kart 8 - (ClintStevens) - June 29, 2021"
  t_start: "00:00:00"
  t_end: "01:59:54"

- video: data/clintstevens/2021-06/1071945223
  title: "Mario Kart Maps Tier List - (ClintStevens) - June 29, 2021"
  t_start: "01:59:54"
  t_end: "02:38:39"

- video: data/clintstevens/2021-07/1075547714
  title: "Mario Kart 8 - (ClintStevens) - July 3, 2021"
  t_start: "00:00:00"
  t_end: "02:23:34"

- video: data/clintstevens/2021-07/1087010008
  title: "Mario Kart 8 - (ClintStevens) - July 14, 2021"
  t_start: "00:00:00"
  t_end: "02:46:18"


- video: data/clintstevens/2021-07/1088119011
  title: "Mario Kart 8 - (ClintStevens) - July 15, 2021"
  t_start: "00:00:00"
  t_end: ""

- video: data/clintstevens/2021-07/1088119011
  title: "Tier List of Stream Snipers - (ClintStevens) - July 15, 2021"
  t_start: "01:54:28"
  t_end: "02:20:00"

- video: data/clintstevens/2021-07/1088119011
  title: "Tier List of Zelda Games - (ClintStevens) - July 15, 2021"
  t_start: "02:20:00"
  t_end: "02:30:00"

- video: data/clintstevens/2021-07/1088119011
  title: "Tier List of Clint's Hoodies - (ClintStevens) - July 15, 2021"
  t_start: "02:30:00"
  t_end: "02:36:26"

- video: data/clintstevens/2021-07/1088119011
  title: "The Legend of Zelda: Skyward Sword HD - Part 1 (ClintStevens) - July 15, 2021"
  t_start: "02:36:26"
  t_end: "05:13:04"

- video: data/clintstevens/2021-07/1089317853
  title: "The Legend of Zelda: Skyward Sword HD - Part 2 (ClintStevens) - July 17, 2021"
  t_start: "00:00:00"
  t_end: "02:42:37"

- video: data/clintstevens/2021-07/1090299644
  title: "The Legend of Zelda: Skyward Sword HD - Part 3 (ClintStevens) - July 18, 2021"
  t_start: "00:00:00"
  t_end: "02:41:16"

- video: data/clintstevens/2021-07/1092278223
  title: "The Legend of Zelda: Skyward Sword HD - Part 4 (ClintStevens) - July 20, 2021"
  t_start: "00:00:00"
  t_end: "02:21:31"

- video: data/clintstevens/2021-07/1093320274
  title: "Mario Kart 8 - (ClintStevens) - July 21, 2021"
  t_start: "00:00:00"
  t_end: "00:14:05"

- video: data/clintstevens/2021-07/1093320274
  title: "Pokémon Unite - (ClintStevens) - July 21, 2021"
  t_start: "00:14:05"
  t_end: "05:15:35"

- video: data/clintstevens/2021-07/1103624624
  title: "Pokémon Unite - (ClintStevens) - July 31, 2021"
  t_start: "00:00:00"
  t_end: "05:32:34"

- video: data/clintstevens/2021-07/1103624624
  title: "Mario Kart 8 - (ClintStevens) - July 31, 2021"
  t_start: "05:31:42"
  t_end: "06:27:17"

- video: data/clintstevens/2021-08/1124794650
  title: "16 Star Race Against Mizkif SM64 w/ Chat - (ClintStevens) - August 20, 2021"
  t_start: "00:01:01"
  t_end: "00:49:36"

- video: data/clintstevens/2021-08/1124794650
  title: "70 Star Runs SM64 w/ Chat - (ClintStevens) - August 20, 2021"
  t_start: "00:49:36"
  t_end: "03:54:22"

- video: data/clintstevens/2021-08/1124794650
  title: "Mario Kart 8 w/ Chat - (ClintStevens) - August 20, 2021"
  t_start: "03:54:22"
  t_end: "05:17:24"

- video: data/clintstevens/2021-08/1125807070
  title: "70 Star Runs SM64 w/ Chat - (ClintStevens) - August 22, 2021"
  t_start: "00:00:00"
  t_end: "05:31:57"

- video: data/clintstevens/2021-08/1125807070
  title: "Mario Kart 8 w/ Chat - (ClintStevens) - August 22, 2021"
  t_start: "05:32:29"
  t_end: "05:53:43"


- video: data/clintstevens/2021-08/1126763254
  title: "70 Star Runs SM64 w/ Chat - (ClintStevens) - August 22, 2021"
  t_start: "00:00:15"
  t_end: "04:54:40"

- video: data/clintstevens/2021-08/1126763254
  title: "Mario Kart 8 w/ Chat - (ClintStevens) - August 22, 2021"
  t_start: "04:56:03"
  t_end: "05:43:27"

- video: data/clintstevens/2021-08/1128780444
  title: "Best Audio (WARNING HEADPHONE USERS) SM64 w/ Chat - (ClintStevens) - August 25, 2021"
  t_start: "00:00:00"
  t_end: "00:01:10"

- video: data/clintstevens/2021-08/1128789069
  title: "70 Star Runs SM64 w/ Chat - (ClintStevens) - August 25, 2021"
  t_start: "00:00:00"
  t_end: "04:56:09"

- video: data/clintstevens/2021-08/1130812100
  title: "70 Star Runs SM64 w/ Chat - (ClintStevens) - August 27, 2021"
  t_start: "00:00:00"
  t_end: "04:13:37"


- video: data/clintstevens/2021-08/1131624558
  title: "Bros vs Pro 16 Star Relay Race w/ Chat - (ClintStevens) - August 27, 2021"
  t_start: "00:00:00"
  t_end: "02:13:15"

- video: data/clintstevens/2021-08/1131624558
  title: "70 Star Race Mizkif w/ Chat - (ClintStevens) - August 27, 2021"
  t_start: "02:13:15"
  t_end: "03:56:51"

- video: data/clintstevens/2021-08/1131624558
  title: "Streamers Play The Game of Life 2 w/ Chat - (ClintStevens) - August 27, 2021"
  t_start: "03:56:51"
  t_end: "05:02:29"

- video: data/clintstevens/2021-08/1131624558
  title: "Streamers Play Fallguys w/ Chat - (ClintStevens) - August 27, 2021"
  t_start: "05:02:29"
  t_end: "07:43:36"

- video: data/clintstevens/2021-08/1133786377
  title: "120 Star Runs SM64 w/ Chat - (ClintStevens) - August 30, 2021"
  t_start: "00:00:00"
  t_end: "04:17:01"

- video: data/clintstevens/2021-08/1133786377
  title: "Mario Kart 8 w/ Chat - (ClintStevens) - August 30, 2021"
  t_start: "04:14:49"
  t_end: "07:19:38"

- video: data/clintstevens/2021-08/1134761883
  title: "120 Star Runs SM64 w/ Chat - (ClintStevens) - August 31, 2021"
  t_start: "00:00:00"
  t_end: "02:52:27"

- video: data/clintstevens/2021-08/1134761883
  title: "Twelve Minutes w/ Chat - (ClintStevens) - August 31, 2021"
  t_start: "02:52:27"
  t_end: "07:15:48"


- video: data/clintstevens/2021-09/1135736265
  title: "120 Star Runs SM64 w/ Chat - (ClintStevens) - September 1, 2021"
  t_start: "00:00:00"
  t_end: "02:56:57"

- video: data/clintstevens/2021-09/1135736265
  title: "Mario Kart 8 w/ Chat - (ClintStevens) - September 1, 2021"
  t_start: "02:56:51"
  t_end: "06:31:36"






