

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/857899012
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Jan 1, 2021"
  t_start: "00:07:52"
  t_end: "03:16:10"

- video: sodapoppin/2021-01/857899012
  title: "Knife Unboxing - (sodapoppin) - Jan 1, 2021"
  t_start: "04:35:18"
  t_end: "04:39:13"

- video: sodapoppin/2021-01/859044247
  title: "Dogs - (sodapoppin) - Jan 2, 2021"
  t_start: "00:10:25"
  t_end: "00:13:28"

- video: sodapoppin/2021-01/859044247
  title: "Rust Part 1 - (sodapoppin) - Jan 2, 2021"
  t_start: "00:13:32"
  t_end: "09:01:31"

- video: sodapoppin/2021-01/860280046
  title: "Rust Part 2 - (sodapoppin) - Jan 3, 2021"
  t_start: "00:15:31"
  t_end: "02:43:40"

- video: sodapoppin/2021-01/860280046
  title: "Risk of Rain 2 with Twitch Integration! - (sodapoppin) - Jan 3, 2021"
  t_start: "02:49:18"
  t_end: "04:34:08"

- video: sodapoppin/2021-01/860280046
  title: "Bloons TD 6 - Day 1 (sodapoppin) - Jan 3, 2021"
  t_start: "04:37:24"
  t_end: "06:28:26"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/861303190
  title: "Chance Reads Twitch's Most Influential Streamer of 2020 (sodapoppin) - Jan 4, 2021"
  t_start: "00:09:41"
  t_end: "00:16:29"

- video: sodapoppin/2021-01/861303190
  title: "Bloons TD 6 with Happythoughts - Day 2 (sodapoppin) - Jan 4, 2021"
  t_start: "00:16:26"
  t_end: "02:30:52"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/862556659
  title: "Bloons TD 6 - Day 3 (sodapoppin) - Jan 5, 2021"
  t_start: "00:13:03"
  t_end: "05:02:27"

- video: sodapoppin/2021-01/862556659
  title: "Escape From Tarkov First Playthrough - (sodapoppin) - Jan 5, 2021"
  t_start: "05:02:12"
  t_end: "07:29:58"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/863793069
  title: "Bloons TD 6 - Day 4 (sodapoppin) - Jan 6, 2021"
  t_start: "00:21:49"
  t_end: "03:23:48"

- video: sodapoppin/2021-01/863793069
  title: "Risk of Rain 2 with Twitch Integration! - (sodapoppin) - Jan 6, 2021"
  t_start: "03:27:08"
  t_end: "03:38:39"

- video: sodapoppin/2021-01/863793069
  title: "Dungeon Defenders with Poke - (sodapoppin) - Jan 6, 2021"
  t_start: "03:38:47"
  t_end: "04:40:13"

- video: sodapoppin/2021-01/863793069
  title: "Escape From Tarkov with Poke - (sodapoppin) - Jan 6, 2021"
  t_start: "04:40:13"
  t_end: "08:23:50"

- video: sodapoppin/2021-01/863793069
  title: "Hades - Day 1 (sodapoppin) - Jan 6, 2021"
  t_start: "08:23:50"
  t_end: "12:43:46"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/865030763
  title: "Hades - Day 2 (sodapoppin) - Jan 7, 2021"
  t_start: "00:10:48"
  t_end: "02:50:44"

- video: sodapoppin/2021-01/865030763
  title: "Rust RP Server Part 1 - (sodapoppin) - Jan 7, 2021"
  t_start: "02:53:10"
  t_end: "12:50:36"

- video: sodapoppin/2021-01/865030763
  title: "Bloons TD 6 - Day 5 - (sodapoppin) - Jan 7, 2021"
  t_start: "10:15:31"
  t_end: "10:29:55"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/866282724
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Jan 8, 2021"
  t_start: "00:13:59"
  t_end: "03:10:21"

- video: sodapoppin/2021-01/866282724
  title: "Rust RP Server Part 2 - (sodapoppin) - Jan 8, 2021"
  t_start: "03:10:25"
  t_end: "09:01:38"

- video: sodapoppin/2021-01/866282724
  title: "Rust RP Server Part 3 - (sodapoppin) - Jan 8, 2021"
  t_start: "09:01:38"
  t_end: "16:10:50"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/867940591
  title: "Rust RP Server Part 4 - (sodapoppin) - Jan 9, 2021"
  t_start: "00:00:00"
  t_end: "11:20:58"

#- video: sodapoppin/2021-01/869168154
#  title: "Rust RP Server Part 5 - (sodapoppin) - Jan 10, 2021"
#  t_start: "00:06:41"
#  t_end: "06:15:02"

#- video: sodapoppin/2021-01/869473500
#  title: "Rust RP Server Part 6 - (sodapoppin) - Jan 11, 2021"
#  t_start: "00:00:00"
#  t_end: "11:15:39"

# ===========================================
# ===========================================

#- video: sodapoppin/2021-01/873748951
#  title: "Rust RP Server Part 7 - (sodapoppin) - Jan 14, 2021"
#  t_start: "00:18:12"
#  t_end: "03:29:14"

- video: sodapoppin/2021-01/873748951
  title: "Bloons TD 6 - Day 6 - (sodapoppin) - Jan 14, 2021"
  t_start: "03:32:22"
  t_end: "04:41:39"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/874806267
  title: "Chance Looks at Community Sizes on Twitch - (sodapoppin) - Jan 15, 2021"
  t_start: "00:25:51"
  t_end: "00:33:51"

- video: sodapoppin/2021-01/874806267
  title: "Chance Plays The Coin Game New Update (survival) - (sodapoppin) - Jan 15, 2021"
  t_start: "00:38:05"
  t_end: "02:08:50"

- video: sodapoppin/2021-01/874806267
  title: "Friday Dungeons & Dragons (flamewrath sodapoppin) - Jan 15, 2021"
  t_start: "02:22:46"
  t_end: "05:36:12"

- video: sodapoppin/2021-01/874806267
  title: "Barotrauma with Vigors, Moonmoon, and Surefour (sodapoppin) - Jan 15, 2021"
  t_start: "05:42:14"
  t_end: "08:05:41"

- video: sodapoppin/2021-01/874806267
  title: "VR Chat with Chance's Dad (sodapoppin) - Jan 15, 2021"
  t_start: "08:12:24"
  t_end: "11:42:16"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/876339259
  title: "Chance Looks at Game Trailers - (sodapoppin) - Jan 16, 2021"
  t_start: "00:15:34"
  t_end: "00:45:08"

- video: sodapoppin/2021-01/876339259
  title: "The Coin Game (survival) - Part 2 (sodapoppin) - Jan 16, 2021"
  t_start: "00:45:08"
  t_end: "02:09:44"

- video: sodapoppin/2021-01/876339259
  title: "Chance and Arcadum Discuss DnD - (sodapoppin) - Jan 16, 2021"
  t_start: "02:16:32"
  t_end: "02:43:47"

- video: sodapoppin/2021-01/876339259
  title: "MADE: Interactive Movie - 01. Run away! - (sodapoppin) - Jan 16, 2021"
  t_start: "02:43:04"
  t_end: "03:27:47"

- video: sodapoppin/2021-01/876339259
  title: "Ultimate Chicken Horse - (sodapoppin) - Jan 16, 2021"
  t_start: "03:33:12"
  t_end: "04:04:29"

- video: sodapoppin/2021-01/876339259
  title: "Chance Plays Sea of Thieves - (sodapoppin) - Jan 16, 2021"
  t_start: "04:17:13"
  t_end: "07:24:50"

# ===========================================
# ===========================================

- video: sodapoppin/2021-01/877652871
  title: "Chance's DnD Studying - (sodapoppin) - Jan 17, 2021"
  t_start: "00:15:26,00:33:18"
  t_end: "00:29:31,00:36:24"

- video: sodapoppin/2021-01/877652871
  title: "Dead by Daylight - (sodapoppin) - Jan 17, 2021"
  t_start: "00:37:34"
  t_end: "03:07:27"

- video: sodapoppin/2021-01/877652871
  title: "Ultimate Chicken Horse - (sodapoppin) - Jan 17, 2021"
  t_start: "03:09:13"
  t_end: "04:00:49"

- video: sodapoppin/2021-01/877652871
  title: "Happy Dog - (sodapoppin) - Jan 17, 2021"
  t_start: "04:01:53,04:34:49"
  t_end: "04:02:47,04:37:17"

- video: sodapoppin/2021-01/877652871
  title: "Worms W.M.D - (sodapoppin) - Jan 17, 2021"
  t_start: "04:03:25"
  t_end: "04:33:23"

- video: sodapoppin/2021-01/877652871
  title: "Chance Plays Depth - (sodapoppin) - Jan 17, 2021"
  t_start: "04:37:31"
  t_end: "05:11:29"

- video: sodapoppin/2021-01/877652871
  title: "Rust RP Server Part 8 -  (sodapoppin) - Jan 17, 2021"
  t_start: "05:11:29"
  t_end: "07:32:07"



