
# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================

# - video: data/sodapoppin/2022-01/1250085833
#   title: "RoboSquare - (sodapoppin) - January 1, 2021"
#   t_start: "00:22:11"
#   t_end: "00:41:37"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "Mologa - (sodapoppin) - January 1, 2021"
#   t_start: "00:45:35"
#   t_end: "00:52:45"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "Car Wash TD: Tower Defense - (sodapoppin) - January 1, 2021"
#   t_start: "00:55:38"
#   t_end: "01:26:37"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "Clownfield 2042 - (sodapoppin) - January 1, 2021"
#   t_start: "01:27:56"
#   t_end: "01:46:49"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "FEWAR DVD - (sodapoppin) - January 1, 2021"
#   t_start: "01:50:36"
#   t_end: "02:01:13"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "Gladio and Glory - (sodapoppin) - January 1, 2021"
#   t_start: "02:02:41"
#   t_end: "02:29:49"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "AI Dungeon - (sodapoppin) - January 1, 2021"
#   t_start: "02:31:17"
#   t_end: "03:30:35"

# - video: data/sodapoppin/2022-01/1250085833
#   title: "Bro Falls: Ultimate Showdown - (sodapoppin) - January 1, 2021"
#   t_start: "03:38:12"
#   t_end: "03:57:21"



# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================

# - video: data/sodapoppin/2022-01/1251974658
#   title: "Risk of Rain 2 - (sodapoppin) - January 3, 2022"
#   t_start: "00:24:09"
#   t_end: "03:00:00"

# - video: data/sodapoppin/2022-01/1251974658
#   title: "For The King - (sodapoppin) - January 3, 2022"
#   t_start: "03:00:00"
#   t_end: "03:52:09"

# - video: data/sodapoppin/2022-01/1251974658
#   title: "The Binding of Isaac: Repentance - (sodapoppin) - January 3, 2022"
#   t_start: "03:53:28"
#   t_end: "05:24:29"

# - video: data/sodapoppin/2022-01/1251974658
#   title: "Pluto Stops by the House - (sodapoppin) - January 3, 2022"
#   t_start: "04:53:34"
#   t_end: "05:09:18"

# - video: data/sodapoppin/2022-01/1251974658
#   title: "Slay the Spire - (sodapoppin) - January 3, 2022"
#   t_start: "05:24:48"
#   t_end: "06:43:32"

# - video: data/sodapoppin/2022-01/1251974658
#   title: "New Wallpaper - (sodapoppin) - January 3, 2022"
#   t_start: "06:45:56"
#   t_end: "06:49:41"



# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================


# - video: data/sodapoppin/2022-01/1254055787
#   title: "Slay the Spire - (sodapoppin) - January 5, 2022"
#   t_start: "00:29:23"
#   t_end: "02:11:35"

# - video: data/sodapoppin/2022-01/1254055787
#   title: "Chance Opens a Puzzel Box - (sodapoppin) - January 5, 2022"
#   t_start: "02:11:48"
#   t_end: "03:37:33"

# - video: data/sodapoppin/2022-01/1254055787
#   title: "Hades - (sodapoppin) - January 5, 2022"
#   t_start: "03:42:16"
#   t_end: "04:22:43"

# - video: data/sodapoppin/2022-01/1254055787
#   title: "Monopoly with VTuber Veibae, Lacari, and Surefour - (sodapoppin) - January 5, 2022"
#   t_start: "04:22:24"
#   t_end: "06:36:17"


# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Propnight - (sodapoppin) - January 6, 2022"
#   t_start: "00:26:36"
#   t_end: "00:42:27"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Dead by Daylight - (sodapoppin) - January 6, 2022"
#   t_start: "00:41:40"
#   t_end: "01:17:22"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Ultimate Chicken Horse - (sodapoppin) - January 6, 2022"
#   t_start: "01:19:35"
#   t_end: "01:41:07"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Who Wants to Be a Millionaire - (sodapoppin) - January 6, 2022"
#   t_start: "01:41:43"
#   t_end: "01:50:59"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Slay the Spire - (sodapoppin) - January 6, 2022"
#   t_start: "01:51:13"
#   t_end: "01:57:23"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Dorfromantik - (sodapoppin) - January 6, 2022"
#   t_start: "02:01:25"
#   t_end: "02:48:21"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Warcraft III - (sodapoppin) - January 6, 2022"
#   t_start: "02:49:20"
#   t_end: "03:41:55"

# - video: data/sodapoppin/2022-01/1255153956
#   title: "Left 4 Dead 2 with Moon, Garek, Vek - (sodapoppin) - January 6, 2022"
#   t_start: "03:40:45"
#   t_end: "05:07:25"



# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================

# - video: data/sodapoppin/2022-01/1257467909
#   title: "Watching Game Trailers - (sodapoppin) - January 8, 2022"
#   t_start: "00:15:18"
#   t_end: "00:35:27"

# - video: data/sodapoppin/2022-01/1257467909
#   title: "Obama Boss Fight - (sodapoppin) - January 8, 2022"
#   t_start: "00:35:40"
#   t_end: "01:14:36"

# - video: data/sodapoppin/2022-01/1257467909
#   title: "Touhou Monster TD - (sodapoppin) - January 8, 2022"
#   t_start: "01:17:14"
#   t_end: "02:31:40"

# - video: data/sodapoppin/2022-01/1257467909
#   title: "Beacon - (sodapoppin) - January 8, 2022"
#   t_start: "02:32:59"
#   t_end: "02:57:00"

# - video: data/sodapoppin/2022-01/1257467909
#   title: "Neon Abyss - (sodapoppin) - January 8, 2022"
#   t_start: "02:58:03"
#   t_end: "04:27:51"

# - video: data/sodapoppin/2022-01/1257467909
#   title: "World of Warcraft - (sodapoppin) - January 8, 2022"
#   t_start: "04:27:16"
#   t_end: "06:37:00"


# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================

# - video: data/sodapoppin/2022-01/1258514670
#   title: "Touhou Monster TD - (sodapoppin) - January 9, 2022"
#   t_start: "00:23:32"
#   t_end: "06:54:27"


# - video: data/sodapoppin/2022-01/1262431443
#   title: "Opening Packages - (sodapoppin) - January 13, 2022"
#   t_start: "00:11:06"
#   t_end: "00:34:44"

# - video: data/sodapoppin/2022-01/1262431443
#   title: "League of Legends - (sodapoppin) - January 13, 2022"
#   t_start: "00:55:25"
#   t_end: "08:01:52"

# - video: data/sodapoppin/2022-01/1263456280
#   title: "League of Legends - (sodapoppin) - January 14, 2022"
#   t_start: "00:40:37"
#   t_end: "06:26:59"


# ===========================================
# https://www.twitch.tv/sodapoppin/videos?filter=all
# ===========================================


# - video: data/sodapoppin/2022-01/1265121554
#   title: "Chance Makes His Coffee - (sodapoppin) - January 15, 2022"
#   t_start: "00:11:11"
#   t_end: "00:18:37"

# - video: data/sodapoppin/2022-01/1265121554
#   title: "Chance Unpacks New Rowing Machine - (sodapoppin) - January 15, 2022"
#   t_start: "00:18:40"
#   t_end: "01:16:16"

# - video: data/sodapoppin/2022-01/1265121554
#   title: "Mental Hospital: Child of Evil (horror) - (sodapoppin) - January 15, 2022"
#   t_start: "01:18:55"
#   t_end: "02:04:43"

# - video: data/sodapoppin/2022-01/1265121554
#   title: "Insomnis (horror) - (sodapoppin) - January 15, 2022"
#   t_start: "02:06:33"
#   t_end: "03:00:36"

# - video: data/sodapoppin/2022-01/1265288797
#   title: "League of Legends - (sodapoppin) - January 15, 2022"
#   t_start: "00:00:27"
#   t_end: "05:39:47"

# - video: data/sodapoppin/2022-01/1266806796
#   title: "League of Legends - (sodapoppin) - January 17, 2022"
#   t_start: "00:22:30"
#   t_end: "06:32:07"



# - video: data/sodapoppin/2022-01/1268502742
#   title: "Chance Reacts to Microsoft Activision Blizzard Aquiring - (sodapoppin) - January 18, 2022"
#   t_start: "00:14:12"
#   t_end: "00:19:20"

- video: data/sodapoppin/2022-01/1268502742
  title: "League of Legends - (sodapoppin) - January 18, 2022"
  t_start: "00:18:02"
  t_end: "05:37:50"

- video: data/sodapoppin/2022-01/1268829976
  title: "League of Legends - (sodapoppin) - January 19, 2022"
  t_start: "00:03:08,00:55:44,01:38:06,02:15:13,02:40:56,03:12:53,03:40:48,04:08:32"
  t_end: "00:40:15,01:14:25,02:07:37,02:34:40,03:03:24,03:38:54,04:04:29,05:42:20"

- video: data/sodapoppin/2022-01/1268829976
  title: "Chance Reacts to Nick's Stream - (sodapoppin) - January 19, 2022"
  t_start: "00:40:15"
  t_end: "00:42:07"

- video: data/sodapoppin/2022-01/1269781795
  title: "Risk of Rain 2 - (sodapoppin) - January 20, 2022"
  t_start: "00:20:59"
  t_end: "01:10:40"

- video: data/sodapoppin/2022-01/1269781795
  title: "League of Legends with Rob - (sodapoppin) - January 20, 2022"
  t_start: "01:11:26"
  t_end: "09:44:14"



