sodapoppin/2021-02/907401075_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_5_(sodapoppin)_-_feb_9,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/907401075_kevin_whipaloo_gta_rp_nopixel_30_-_part_5_sodapoppin_-_feb_9_2021.mp4
  link: https://www.youtube.com/watch?v=e_txSLdN-vk
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 5 (sodapoppin) - Feb 9, 2021
sodapoppin/2021-02/909117058_chance_watches_maya's_charity_stream_for_alveus_sanctuary_-_(sodapoppin)_-_feb_10,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/909117058_chance_watches_mayas_charity_stream_for_alveus_sanctuary_-_sodapoppin_-_feb_10_2021.mp4
  link: https://www.youtube.com/watch?v=MpBqSV4cgbY
  title: Chance Watches Maya's Charity Stream for Alveus Sanctuary - (sodapoppin)
    - Feb 10, 2021
sodapoppin/2021-02/909117058_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_6_(sodapoppin)_-_feb_10,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/909117058_kevin_whipaloo_gta_rp_nopixel_30_-_part_6_sodapoppin_-_feb_10_2021.mp4
  link: https://www.youtube.com/watch?v=dnZ0w6CgV3o
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 6 (sodapoppin) - Feb 10, 2021
sodapoppin/2021-02/910719989_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_7_(sodapoppin)_-_feb_11,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/910719989_kevin_whipaloo_gta_rp_nopixel_30_-_part_7_sodapoppin_-_feb_11_2021.mp4
  link: https://www.youtube.com/watch?v=ll10Ags7qRw
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 7 (sodapoppin) - Feb 11, 2021
sodapoppin/2021-02/911560267_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_feb_12,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/911560267_friday_dungeons__dragons_flamewrath_sodapoppin_-_feb_12_2021.mp4
  link: https://www.youtube.com/watch?v=lEyU17WfwzY
  title: Friday Dungeons & Dragons (flamewrath sodapoppin) - Feb 12, 2021
sodapoppin/2021-02/911560267_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_8_(sodapoppin)_-_feb_12,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/911560267_kevin_whipaloo_gta_rp_nopixel_30_-_part_8_sodapoppin_-_feb_12_2021.mp4
  link: https://www.youtube.com/watch?v=eNjw93Suan8
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 8 (sodapoppin) - Feb 12, 2021
sodapoppin/2021-02/913197786_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_9_(sodapoppin)_-_feb_13,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/913197786_kevin_whipaloo_gta_rp_nopixel_30_-_part_9_sodapoppin_-_feb_13_2021.mp4
  link: https://www.youtube.com/watch?v=Lkt6VszhDaY
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 9 (sodapoppin) - Feb 13, 2021
sodapoppin/2021-02/914612619_birthday_gift_box_opening_-_(sodapoppin)_-_feb_14,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/914612619_birthday_gift_box_opening_-_sodapoppin_-_feb_14_2021.mp4
  link: https://www.youtube.com/watch?v=P0niTu0APuA
  title: Birthday Gift Box Opening - (sodapoppin) - Feb 14, 2021
sodapoppin/2021-02/914612619_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_10_(sodapoppin)_-_feb_14,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/914612619_kevin_whipaloo_gta_rp_nopixel_30_-_part_10_sodapoppin_-_feb_14_2021.mp4
  link: https://www.youtube.com/watch?v=-wwgygs00po
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 10 (sodapoppin) - Feb 14, 2021
sodapoppin/2021-02/915349327_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_11_(sodapoppin)_-_feb_15,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/915349327_kevin_whipaloo_gta_rp_nopixel_30_-_part_11_sodapoppin_-_feb_15_2021.mp4
  link: https://www.youtube.com/watch?v=FK51yHPDf3U
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 11 (sodapoppin) - Feb 15, 2021
sodapoppin/2021-02/916683501_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_12_(sodapoppin)_-_feb_16,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/916683501_kevin_whipaloo_gta_rp_nopixel_30_-_part_12_sodapoppin_-_feb_16_2021.mp4
  link: https://www.youtube.com/watch?v=iFgw0fMAEB0
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 12 (sodapoppin) - Feb 16, 2021
sodapoppin/2021-02/919221745_kevin_whipaloo_gta_rp_nopixel_3.0_-_part_13_(sodapoppin)_-_feb_18,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/919221745_kevin_whipaloo_gta_rp_nopixel_30_-_part_13_sodapoppin_-_feb_18_2021.mp4
  link: https://www.youtube.com/watch?v=EvaWUddx1RA
  title: Kevin Whipaloo GTA RP NoPixel 3.0 - Part 13 (sodapoppin) - Feb 18, 2021
sodapoppin/2021-02/920434187_chance_plays_ssx_tricky_-_(sodapoppin)_-_feb_19,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/920434187_chance_plays_ssx_tricky_-_sodapoppin_-_feb_19_2021.mp4
  link: https://www.youtube.com/watch?v=FS7cKS2lFZA
  title: Chance Plays SSX Tricky - (sodapoppin) - Feb 19, 2021
sodapoppin/2021-02/920434187_chance_watches_blizzcon_-_(sodapoppin)_-_feb_19,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/920434187_chance_watches_blizzcon_-_sodapoppin_-_feb_19_2021.mp4
  link: https://www.youtube.com/watch?v=qvuHBK-qDyw
  title: Chance Watches BlizzCon - (sodapoppin) - Feb 19, 2021
sodapoppin/2021-02/920434187_chance_watches_stuck_in_america_music_video_-_(sodapoppin)_-_feb_19,_2021:
  file: /mnt/VAULT/twitch_vod_creator/../data_rendered/sodapoppin/2021-02/920434187_chance_watches_stuck_in_america_music_video_-_sodapoppin_-_feb_19_2021.mp4
  link: https://www.youtube.com/watch?v=R4JHZZCG4eA
  title: Chance Watches Stuck in America Music Video - (sodapoppin) - Feb 19, 2021
